### PR TITLE
Fix secure cookie

### PR DESCRIPTION
**Pull request by tinohager**
This solution works in my case with chrome

```
version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - oidc-server-mock
    restart: always
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://oidc-server-mock:80'

  oidc-server-mock:
    container_name: oidc-server-mock
    image: soluto/oidc-server-mock
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          }
        }
      API_SCOPES_INLINE: |
        [
          "some-app-scope-1",
          "some-app-scope-2"
        ]
      API_RESOURCES_INLINE: |
        [
          {
            "Name": "some-app",
            "Scopes": ["some-app-scope-1", "some-app-scope-2"]
          }
        ]
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1",
            "Username":"admin",
            "Password":"password1234"
          }
        ]
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
    volumes:
      - .:/tmp/config:ro
```

### CODE REVIEW

**Comment by tinohager** [comment]
`https://localhost/.well-known/openid-configuration` without the `Add reverse proxy forward logic` pull we have the `issuer` with the wrong value `oidc-server-mock`

**Comment by tinohager** [comment]
If you start the mock on localhost and Let’s Encrypt is not available. You can add your own certificate with this solution.

```
  reverseproxy:
    image: nginx:1.19.2
    command: |
      bash -c 'bash -s <<EOF
      cat > /etc/nginx/your_site_crt_file.crt <<EON
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
      EON
      cat > /etc/nginx/your_site_crt_file.key <<EON
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
      EON
      cat > /etc/nginx/nginx.conf <<EON
        daemon off;
        user www-data;
        events {
          worker_connections 768;
        }
        http {
          gzip on;
          gzip_disable "msie6";
          include /etc/nginx/mime.types;
          client_max_body_size 16M;
          server {
            listen 80;
            listen 443 ssl;
            ssl_certificate /etc/nginx/your_site_crt_file.crt;
            ssl_certificate_key /etc/nginx/your_site_crt_file.key;
            location / {
              proxy_set_header Host localhost;
              proxy_set_header X-Forwarded-Proto https;
              proxy_pass http://oidc-server-mock;
              proxy_intercept_errors on;
            }
          }
        }
      EON
      nginx
      EOF'
    links:
      - oidc-server-mock
    restart: always
    ports:
      - 80:80
      - 443:443
```

**Comment by tinohager** [comment]
Move certificate files in a folder `certificate` with this two files are requires `selfsigned.crt` `selfsigned.key` 

```
version: '3'
services:
  entrypoint:
    image: nginx:1.19.2
    command: |
      bash -c 'bash -s <<EOF
      cat > /etc/nginx/nginx.conf <<EON
        daemon off;
        user www-data;
        events {
          worker_connections 768;
        }
        http {
          gzip on;
          gzip_disable "msie6";
          include /etc/nginx/mime.types;
          client_max_body_size 16M;
          server {
            listen 80;
            listen 443 ssl;
            ssl_certificate /etc/nginx/certificate/selfsigned.crt;
            ssl_certificate_key /etc/nginx/certificate/selfsigned.key;
            location / {
              proxy_set_header Host localhost;
              proxy_set_header X-Forwarded-Proto https;
              proxy_pass http://oidc-server-mock;
              proxy_intercept_errors on;
            }
          }
        }
      EON
      nginx
      EOF'
    links:
      - oidc-server-mock
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certificate:/etc/nginx/certificate/:ro
```

**Comment by AleF83** [comment]
Thank you for helping.
I'm not familiar with the cookie issue (I didn't encountered it in my scenarios).
So I'm learning about it now. 
I'm trying to fix the issue with the inspiration of your PR but in more configurable approach as I mentioned https://github.com/Soluto/oidc-server-mock/issues/25#issuecomment-670066032

So as the first step I want to enable AspNet server configuration via env vars:
https://github.com/Soluto/oidc-server-mock/pull/45

And then I want to add tests for the issue.
Can you describe the scenario that causes the failure in Chrome browser.

**Comment by tinohager** [comment]
If i start your docker image an try login `http://localhost/Account/Login?ReturnUrl=%2Fgrants`, the login not work.
I use Chrome `85.0.4183.121`
image
image

**Comment by AleF83** [comment]
Got it.
I'll fix it ASAP.

**Comment by tinohager** [comment]
`*.sh text eol=lf` this fix the .sh script have wrong linefeed and not work in docker build

**Pull request closed without merging**
