### PR TITLE
Adds support for client claims configuration

### PR DESCRIPTION
**Pull request by vitalyal**
Hello, this enables possibility to configure custom claims for clients

### CODE REVIEW

**Comment by vitalyal** [comment]
Hello @AleF83, when you have time could you please provide feedback on this PR

**Comment by AleF83** [comment]
Hi, merged!
Sorry for delay, we have holidays now :-)
Thank you for contributing!

**Comment by vitalyal** [comment]
Thanks! Have a great holidays and sorry for disturbing on holidays :)

**Comment by vitalyal** [comment]
Hi @AleF83 , when you have time after holidays could you be so kind to publish updated image to docker hub :)

**Comment by AleF83** [comment]
Sorry, forgot it. Done.

**Comment by vitalyal** [comment]
NP, thanks a lot!

**Pull request merged**
